service: lambdasys-serverless-project
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'
  region: sa-east-1
  iam: 
    role: 
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:GetItem
            - dynamodb:scan
            - dynamodb:DeleteItem
          Resource:
            - arn:aws:dynamodb:sa-east-1:${account-code}:table:ItemTableNew



functions:
  hello:
    handler: src/handler.hello
    events:
      - httpApi:
          path: /
          method: get
  insertItem:
    handler: src/insertitem.handler
    events:
      - httpApi:
          path: /items 
          method: post 
  updateItem:
    handler: src/updateitem.handler
    events: 
      - httpApi: 
          path: /items/{id} 
          method: put
  getItems:
    handler: src/getItems.handler
    events:
      - httpApi:
          path: /items                
          method: get 
  getItem:
    handler: src/getItem.handler
    events:
      - httpApi:
          path: /items/{id}                
          method: get 
  deleteItem:
    handler: src/deleteItem.handler
    events:
      - httpApi:
          path: /items/{id}
          method: delete

resources:
  Resources:
    ItemTableNew:
      Type: AWS::DynamoDB::ItemTableNew
      Properties:
        TableName: ItemTableNew
        BillingMode: PAY_PER_REQUEST
        AttributteDefinitions: 
          - AttributeName: id 
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH    